{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "768a8364-2f96-42c4-986e-734f3b9b0f02",
      "group": 0,
      "instanceID": "93dca0f9-98c6-4ce3-8158-e2c8db3036cb",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "cc8abcad-c9b0-4050-925a-bc77f8bf5a18",
      "group": 0,
      "instanceID": "685f6432-c2f6-4d4d-a96f-bce78fff850c",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "33f3fb04-040a-4da0-a473-05c8b88bb1e0",
      "group": 0,
      "instanceID": "6cde9208-f65a-478a-ac0b-dcded0c554c9",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "51421182-3138-47a6-a8cf-3991990e9815",
  "name": "SeenOrHeardOverrides-DefaultBlock"
}