{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "67e91b8c-c0ac-4895-98f6-d24c90bc3562",
      "group": 0,
      "instanceID": "6854e087-c7b9-44c0-8d27-62074f3d5cf1",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "a6a9b0cf-7302-4047-a745-b269089baf15",
      "group": 0,
      "instanceID": "d89a345e-c74d-4db9-a795-ea75d37d5e15",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "e07bb9c7-cefb-4c6e-b6c0-d8e02f980df6",
      "group": 0,
      "instanceID": "e31cff81-b9ae-4bda-98fb-bb71f0340c8f",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "c9144f21-ae8f-49f3-a0e8-40cf4f5e5c18",
      "group": 0,
      "instanceID": "06968925-2956-498c-8cc9-61ba50b46d5b",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "b8591738-092c-4de6-992e-33a44d6ab43f",
  "name": "SeenOrHeardOverrides-DefaultBlock"
}