{
  "name": "Passcode_Reminder01_CrumpledBin",
  "id": "9e80e7cd-feea-4355-bf9a-852fd571b0c1",
  "blocks": [
    {
      "blockID": "3316413a-a2ef-462a-8f31-851060ea3c13",
      "instanceID": "91c47dcc-01ce-4e65-96d5-d741a38e930f",
      "alwaysDisplay": false,
      "group": 0,
      "forceScope": 0,
      "useTraits": false,
      "traitConditions": 0,
      "traits": []
    },
    {
      "blockID": "6c4f4d9f-4505-4ead-89f8-42ae1aaf340f",
      "instanceID": "db97fba9-c3d8-4257-975b-185fdd8ef8a4",
      "alwaysDisplay": false,
      "group": 0,
      "forceScope": 0,
      "useTraits": false,
      "traitConditions": 0,
      "traits": []
    },
    {
      "blockID": "e419e9e5-daf3-4b15-b308-dc9ce7db4f8d",
      "instanceID": "6c5f59f8-0c80-4b70-a0c6-a5113fa8936b",
      "alwaysDisplay": false,
      "group": 0,
      "forceScope": 0,
      "useTraits": false,
      "traitConditions": 0,
      "traits": []
    },
    {
      "blockID": "40f29a79-6953-4f8e-89f7-af42784a7960",
      "instanceID": "6c8bdd82-c7e0-47f3-b888-32e3c4d208a0",
      "alwaysDisplay": false,
      "group": 0,
      "forceScope": 0,
      "useTraits": true,
      "traitConditions": 0,
      "traits": [
        "Char-Detached",
        "Char-Ditzy"
      ]
    },
    {
      "blockID": "94ca17f3-c1df-4d19-ad20-6ee02c20b421",
      "instanceID": "fecfed8a-3a99-4042-b76f-84c6a644fc9c",
      "alwaysDisplay": false,
      "group": 0,
      "forceScope": 0,
      "useTraits": true,
      "traitConditions": 0,
      "traits": []
    },
    {
      "blockID": "26db698e-5dd7-4dc1-b5a7-8db101055201",
      "instanceID": "b155e1b2-f159-4801-a2ff-7a217e87a734",
      "alwaysDisplay": true,
      "group": 0,
      "forceScope": 0,
      "useTraits": false,
      "traitConditions": 0,
      "traits": []
    },
    {
      "blockID": "2d4b80f0-8ec8-46d5-9808-f50de0bf5c6c",
      "instanceID": "a6538d84-29fd-4e2c-9ac0-75509126a4bf",
      "alwaysDisplay": false,
      "group": 0,
      "forceScope": 0,
      "useTraits": true,
      "traitConditions": 0,
      "traits": [
        "Char-Anxious",
        "Char-Cautious"
      ]
    },
    {
      "blockID": "97ea8807-2305-45ef-831c-f3b8b4192241",
      "instanceID": "14e20afb-8ebe-4150-8af3-dc8ade947fc7",
      "alwaysDisplay": false,
      "group": 0,
      "forceScope": 0,
      "useTraits": true,
      "traitConditions": 0,
      "traits": [
        "Char-Cautious"
      ]
    },
    {
      "blockID": "2d4822fc-b3c3-4c1d-a434-e4d827c5354d",
      "instanceID": "7a577091-7310-4417-9bad-35cdb8775aa9",
      "alwaysDisplay": false,
      "group": 0,
      "forceScope": 0,
      "useTraits": true,
      "traitConditions": 0,
      "traits": [
        "Char-Cautious",
        "Char-Obsessive"
      ]
    }
  ]
}