{
 "name": "PolicyLedger-Body",
 "id": "0a1c14a7-9488-4d70-b77a-db46cb652c70",
 "blocks": [
  {
   "blockID": "84ebb160-1c65-408f-b05c-5ec3a219cb79",
   "instanceID": "c940c020-3491-4adb-a6a3-76e500421f3a",
   "alwaysDisplay": true,
   "group": 0,
   "forceScope": 0,
   "useTraits": false,
   "traitConditions": 0,
   "traits": []
  },
  {
   "blockID": "e93a4131-3cce-4a03-855a-4ee8d033b99c",
   "instanceID": "7c625595-27f7-40b4-959b-fc149faa81e3",
   "alwaysDisplay": true,
   "group": 0,
   "forceScope": 0,
   "useTraits": false,
   "traitConditions": 0,
   "traits": []
  },
  {
   "blockID": "17fa83c5-221b-4f52-a845-ee0c24595189",
   "instanceID": "aaebea0a-82fe-4f22-a16e-6960f3feb090",
   "alwaysDisplay": true,
   "group": 0,
   "forceScope": 0,
   "useTraits": false,
   "traitConditions": 0,
   "traits": []
  },
  {
   "blockID": "4ff3b495-8193-402c-b616-94972b29508a",
   "instanceID": "c51ba0f5-9452-41bd-afb0-f356247bdb01",
   "alwaysDisplay": true,
   "group": 0,
   "forceScope": 0,
   "useTraits": false,
   "traitConditions": 0,
   "traits": []
  },
  {
   "blockID": "b5c24556-61f3-4f20-a982-9a338871412c",
   "instanceID": "6cdfb1e1-2b73-42be-8383-92930622f10f",
   "alwaysDisplay": true,
   "group": 0,
   "forceScope": 0,
   "useTraits": false,
   "traitConditions": 0,
   "traits": []
  },
  {
   "blockID": "79abbe90-73c6-4d31-8e0a-c07afed5f7ab",
   "instanceID": "4d5e1d2b-755a-4012-9a7c-df2dea3f6864",
   "alwaysDisplay": true,
   "group": 0,
   "forceScope": 0,
   "useTraits": false,
   "traitConditions": 0,
   "traits": []
  },
  {
   "blockID": "5d24bafe-ad99-49cc-8d44-79884932fecb",
   "instanceID": "9dc06559-53d1-4c8b-8057-b10618a8cf13",
   "alwaysDisplay": true,
   "group": 0,
   "forceScope": 0,
   "useTraits": false,
   "traitConditions": 0,
   "traits": []
  },
  {
   "blockID": "17ca5787-b3fb-4955-8a68-b1f2271e268d",
   "instanceID": "7a13e948-5bc4-4d8d-a6a0-e9ee5e71c44b",
   "alwaysDisplay": true,
   "group": 0,
   "forceScope": 0,
   "useTraits": false,
   "traitConditions": 0,
   "traits": []
  }
 ]
}