{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "7fa383e0-3942-4d6e-bff4-f2164dd5b1ca",
      "forceScope": 0,
      "group": 0,
      "instanceID": "1e2fc709-8128-4bd0-919e-ab098b60faee",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "fb46f8b5-0395-48f5-8b10-cf07084eca5c",
      "forceScope": 0,
      "group": 0,
      "instanceID": "1faa08a1-bae6-4e1d-a1e9-f1939c2c5bad",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "00deca74-9ad8-458d-b32f-9addf069e817",
  "name": "Murder_Hitman_Orders_Vmail"
}