{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "c22aec5a-4d23-4622-b428-2008daa682cd",
      "forceScope": 0,
      "group": 0,
      "instanceID": "315acb01-6434-4abf-9395-a7acb071dc45",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "6d51ff5e-9d9c-4bb8-9ad5-43a17dd40cb1",
      "forceScope": 0,
      "group": 0,
      "instanceID": "45e043e5-08c4-4bea-9e0d-de53e146718f",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "795afb08-f6e1-43fa-ac76-0c59ddcb25b7",
  "name": "HitmanHirePhonecallFailure"
}