{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "25c73c10-3ffa-436b-9ea5-b6151147a6b3",
      "forceScope": 0,
      "group": 0,
      "instanceID": "98a160e9-94d3-416f-b9df-2981c9da07a7",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "bc1f07db-e58a-4065-b07a-5b5addb2e3a9",
      "forceScope": 0,
      "group": 0,
      "instanceID": "14cc7aeb-1cbc-44c2-a2f9-3a5d08e4d01a",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "f9ecdef0-1a1b-43db-a6c8-fead34f4036d",
  "name": "VMailNoiseComplaintToBuildingSecMessage"
}