{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "aac4c134-0767-4102-bec7-50b92af8b454",
      "forceScope": 0,
      "group": 0,
      "instanceID": "3365f74b-b11b-4ec2-b4ab-a95946907129",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "cf940843-f2ed-4886-bf73-6b338fa85716",
      "forceScope": 0,
      "group": 0,
      "instanceID": "73a5ff99-55e0-4ac6-9adc-6e06457620b0",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "66da9109-6801-4e14-9847-d235648dfed0",
  "name": "AnalysisRejectedNotAtWork"
}