{
  "blocks": [
    {
      "alwaysDisplay": false,
      "blockID": "44cbebc8-71f2-4770-b61f-ddb0c949b90f",
      "group": 0,
      "instanceID": "3a2fa4dd-c9a7-455e-ab38-d907f722f179",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "a4040d87-bd2b-4ee9-80fa-4c00d72eaa19",
      "forceScope": 0,
      "group": 0,
      "instanceID": "11d75cf8-5c63-41e2-befe-3c43a912b3c6",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "7a349752-849f-4ed8-b764-772bed8b3f61",
      "forceScope": 0,
      "group": 0,
      "instanceID": "68f6dfc0-73b9-40e2-8a11-804f0c5cec40",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "e345805d-b110-4229-a2a6-2687a4c112a7",
      "forceScope": 0,
      "group": 0,
      "instanceID": "e4042331-be7a-49e9-948b-198152ec8dc7",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "1435a1d4-465f-49df-98c5-12ad5515ff8d",
  "name": "TalkToPartner-Success"
}