{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "44cbebc8-71f2-4770-b61f-ddb0c949b90f",
      "group": 0,
      "instanceID": "3a2fa4dd-c9a7-455e-ab38-d907f722f179",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "|partner.casualname|! Somebody is at the door for you!",
      "group": 0,
      "instanceID": "bd2e2a9e-2201-4ef8-8bdd-11123763eca2",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "1435a1d4-465f-49df-98c5-12ad5515ff8d",
  "name": "TalkToPartner-Success"
}