{
  "blocks": [
    {
      "alwaysDisplay": false,
      "blockID": "e447a8e8-0c20-46a0-9082-59ade79f8dfc",
      "group": 1,
      "instanceID": "b51a5510-c811-4483-b6cc-ef0a4654c8ca",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "6a2c1911-0a40-4f92-ab0e-ef2021f5bc8c",
      "group": 1,
      "instanceID": "59118866-6c81-4648-b590-cc3f8deb412a",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "6b130ac4-3031-4cdd-987f-0ccd07244fd4",
      "forceScope": 0,
      "group": 1,
      "instanceID": "524f431f-c578-4c06-a225-22ac774a59b6",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "4f7266c4-a631-482b-8798-074428d66a55",
  "name": "TalkToPartner-NoPartner"
}