{
  "blocks": [
    {
      "alwaysDisplay": false,
      "blockID": "696bde6a-f80d-413e-b504-f036be0bba99",
      "group": 1,
      "instanceID": "517e6b6a-135f-4f25-9b50-44bcc9af435e",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "5389a504-832a-4c75-aee2-925a8deebb01",
      "group": 1,
      "instanceID": "6eb6b476-c9cb-4689-a996-189311f8d57f",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "ea749543-c1cd-4388-938d-a0ccff59d292",
      "forceScope": 0,
      "group": 1,
      "instanceID": "ded6a94a-05a6-44ff-ba35-da93b88b72f0",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "57572420-51ad-4b2c-a9dd-8827c695a222",
      "forceScope": 0,
      "group": 1,
      "instanceID": "ddb11f4a-4a60-4839-8698-e9da040cdccd",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "9f436995-fd25-4116-8eab-68509be5721b",
  "name": "TalkToPartner-NotHome"
}