{
  "name": "TalkToPartner-Fail",
  "id": "b7d97901-3d58-4cdc-afc2-34003de5192b",
  "blocks": [
    {
      "blockID": "ade4aafa-8355-43f6-96b9-32aa115be125",
      "instanceID": "5af7581a-a8b3-4613-bf2e-9f7150ebe067",
      "alwaysDisplay": false,
      "group": 1,
      "forceScope": 0,
      "useTraits": true,
      "traitConditions": 0,
      "traits": [
        "Char-Abrasive",
        "Char-Aloof",
        "Char-Dramatic",
        "Char-Grumpy",
        "Char-Guarded",
        "Char-Hostile",
        "Char-Obnoxious",
        "Char-Paranoid",
        "Char-Selfish",
        "Char-ShortTemper",
        "Char-Suspicious"
      ]
    },
    {
      "blockID": "efc78169-d5cf-42e6-9d07-2d7f863da416",
      "instanceID": "dda416c9-898e-401d-8855-fa4a908eba82",
      "alwaysDisplay": false,
      "group": 1,
      "forceScope": 0,
      "useTraits": false,
      "traitConditions": 0,
      "traits": []
    },
    {
      "blockID": "55ff373b-8a4d-4156-88d2-0a928287f916",
      "instanceID": "442518ae-9500-478d-bcfe-358a9af118d1",
      "alwaysDisplay": false,
      "group": 1,
      "forceScope": 0,
      "useTraits": false,
      "traitConditions": 0,
      "traits": []
    },
    {
      "blockID": "129f2662-df16-4922-9fa1-666e897ce65f",
      "instanceID": "49fcbc16-99de-42ea-a313-81613df2a6eb",
      "alwaysDisplay": false,
      "group": 1,
      "forceScope": 0,
      "useTraits": true,
      "traitConditions": 0,
      "traits": []
    },
    {
      "blockID": "7ba6cba7-11f5-40e1-85a9-516348daaac6",
      "instanceID": "3b6d5930-3ab4-44a2-9367-1ca042108b72",
      "alwaysDisplay": false,
      "group": 1,
      "forceScope": 0,
      "useTraits": true,
      "traitConditions": 0,
      "traits": [
        "Char-Cautious",
        "Char-Friendly",
        "Char-Guarded",
        "Char-Honest",
        "Char-Polite"
      ]
    },
    {
      "blockID": "ad372526-05dc-43e9-ace9-4480358fd244",
      "instanceID": "0889ca3f-f31b-421f-bc2e-6df54b92dcd1",
      "alwaysDisplay": false,
      "group": 1,
      "forceScope": 0,
      "useTraits": true,
      "traitConditions": 0,
      "traits": [
        "Char-Aloof",
        "Char-Anxious",
        "Char-Cautious",
        "Char-Awkward",
        "Char-Coward",
        "Char-Guarded",
        "Char-Introverted",
        "Char-Paranoid",
        "Char-Polite",
        "Char-Rational",
        "Char-Tactful",
        "Char-LevelHeaded"
      ]
    }
  ]
}