{
    "blocks": [
        {
            "alwaysDisplay": true,
            "blockID": "019b4861-a08d-45c6-b7ce-c444bb53fa00",
			"forceScope": 0,
            "group": 0,
            "instanceID": "70255550-98f7-43ed-a686-f65179670ca9",
            "traitConditions": 0,
            "traits": [
            ],
            "useTraits": false
        }
    ],
    "id": "cfa7463c-a03d-4c2c-87e9-124a39290716",
    "name": "TalkToPartner-PlayerStart"
}