{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "14d2a997-ce0c-4206-a299-769c3717e9ee",
      "group": 0,
      "instanceID": "961d9747-5647-4d68-9431-c6e06d373107",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
	{
      "alwaysDisplay": true,
      "blockID": "19b62535-1d8f-4256-95e0-4a1827519202",
      "group": 1,
      "instanceID": "7b4342df-54a6-4e0b-a5d9-1e065d8ef0fc",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "669bd28e-22fd-4db7-8b64-c4425ed7b0e7",
  "name": "SeenThisPersonWithOthers-DefaultBlock"
}