{
    "blocks": [
            {
      "alwaysDisplay": true,
      "blockID": "14d2a997-ce0c-4206-a299-769c3717e9ee",
      "group": 0,
      "instanceID": "961d9747-5647-4d68-9431-c6e06d373107",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },{
            "alwaysDisplay": true,
            "blockID": "ea1a4b54-36b8-4f4c-a441-4031bec76501",
            "group": 0,
            "instanceID": "595fb957-b085-46fe-801a-7de11fc699a2",
            "traitConditions": 0,
            "traits": [
            ],
            "useTraits": false
        }
    ],
    "id": "76ec3908-68e5-4238-bc2e-57545ce46850",
    "name": "SeenThisPersonWithOthers-DefaultBlock"
}