{
    "blocks": [
            {
      "alwaysDisplay": true,
      "blockID": "14d2a997-ce0c-4206-a299-769c3717e9ee",
      "group": 0,
      "instanceID": "961d9747-5647-4d68-9431-c6e06d373107",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },{
            "alwaysDisplay": true,
            "blockID": "385f5635-bf55-421d-b7a2-bbecc8e6489e",
            "group": 0,
            "instanceID": "ed3ef835-4ca3-4c6d-9829-72fff0d8c977",
            "traitConditions": 0,
            "traits": [
            ],
            "useTraits": false
        }
    ],
    "id": "d5af67b2-9c85-41f1-a703-add0be0b1ddf",
    "name": "SeenThisPersonWithOthers-DefaultBlock"
}