{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "a6c0ed45-74a7-4b39-8d19-bf98b1ee713f",
      "group": 0,
      "instanceID": "59a8493f-a780-4db3-96c6-60dc3eb560e3",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "ae33a1a5-e356-4e8f-8d43-d0d63449998e",
      "group": 0,
      "instanceID": "0abc0902-97a2-455b-b30e-94b60fd1e279",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "c576a17b-6c96-4bcb-b0f4-3f8585f2e246",
      "forceScope": 0,
      "group": 0,
      "instanceID": "a08d1a38-4a86-432a-813f-00edaabc866b",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "b218c9bc-e248-4ba0-a33d-217379b55516",
      "group": 0,
      "instanceID": "b13815a8-b28a-41d8-bedc-b7549e50891d",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "a6762364-fe13-4d61-ab01-0112485af2fc",
      "group": 0,
      "instanceID": "c4cca7f7-40bf-498d-bcd6-38cfcf3cf029",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "de666906-a6ff-4e3c-8083-e6b3d5bffc69",
      "forceScope": 0,
      "group": 0,
      "instanceID": "2098cbaf-bba4-4803-a042-84f038493ae6",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "a21abf62-aec5-4dc5-954b-445fdb297e25",
  "name": "CorporateJealousy-DefaultBlock"
}