{
    "blocks": [
        {
            "alwaysDisplay": false,
            "blockID": "8dff9b13-996f-4f26-adda-84e51138983e",
            "group": 1,
            "instanceID": "6b059b48-917a-442f-8c22-6fe70d69d98f",
            "traitConditions": 0,
            "traits": [
            ],
            "useTraits": false
        }
    ],
    "id": "319cb03a-2616-43e5-83af-40b96a801b1c",
    "name": "MonkierTheftGoneWrong"
}