{
    "blocks": [
        {
            "alwaysDisplay": true,
            "blockID": "cb1df24c-3a75-4c26-9cb5-7df909e17c8f",
            "forceScope": 0,
            "group": 0,
            "instanceID": "98db7c83-8bf8-4bda-97d5-d5824ca97d80",
            "traitConditions": 0,
            "traits": [
            ],
            "useTraits": false
        }
    ],
    "id": "59fd3ae9-d646-4ee2-a8ea-b2bb2961ba1a",
    "name": "CrumpledNoteStickup"
}