{
  "blocks": [
    {
      "alwaysDisplay": false,
      "blockID": "66704edd-6c60-4b6f-a753-5adcbf330a57",
      "forceScope": 0,
      "group": 1,
      "instanceID": "a3f9329e-ba75-400c-84e5-99fe3b2b1faf",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "eb11d7d3-60af-4514-8ba9-63a93df297d9",
      "forceScope": 0,
      "group": 1,
      "instanceID": "453011b8-c90c-4954-bfde-c1d83b25d916",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": false,
      "blockID": "68c81197-db41-4ff5-a94b-483279cf9244",
      "forceScope": 0,
      "group": 1,
      "instanceID": "176f9a10-1c7a-49d9-938f-35e6125bfecf",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "79450f40-a776-4e00-b676-719fadc99e8b",
  "name": "Know_Favourite_Bar_No_Name"
}