{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "34cb095b-b77a-4487-ab7a-0df8a9c0832a",
      "forceScope": 0,
      "group": 0,
      "instanceID": "e3cc7ba5-e745-4615-bec2-8b45361d147d",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "6cc80a5d-70b9-4dca-a623-2e7d4f5a9e7e",
      "forceScope": 0,
      "group": 0,
      "instanceID": "5abbb6b4-461c-412a-acfa-df381fd2c9a8",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "dcf09b3f-5444-407b-af26-2265e65dc628",
      "forceScope": 0,
      "group": 0,
      "instanceID": "54097243-a92d-41f9-aa0b-b4d8a9bb5e6b",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "30c2f92a-eaf5-4f95-b086-6341e84511db",
  "name": "SideJobFinanceInvestigatorOffice-DefaultBlock"
}