{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "41c735ad-9d15-4613-a5b1-d6a3dc8085c8",
      "forceScope": 0,
      "group": 0,
      "instanceID": "70b662f4-79c4-4f4e-adbb-db0a560f7115",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "76860e42-914f-4b4f-addb-111e6abed2fb",
      "forceScope": 0,
      "group": 0,
      "instanceID": "7d7498b6-3859-462e-9bec-1e40f408480d",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "35fe5619-4f5a-4525-bd91-5ba90b283f8a",
      "forceScope": 0,
      "group": 0,
      "instanceID": "09cea259-c493-4a99-bbb2-e27f163d5d4f",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "d9878574-c5de-4ab4-86af-004a0bc13d63",
      "forceScope": 0,
      "group": 0,
      "instanceID": "96de0e21-5a51-42e6-bf3b-d77e3fb6191b",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "f7b0ed68-f653-4df9-8eef-0e58beeb2837",
      "forceScope": 0,
      "group": 0,
      "instanceID": "ec1ac6a7-116a-4b44-b378-c0b5f4999b6a",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "c2e898b9-7442-46aa-9e88-3ecafa81d232",
      "forceScope": 0,
      "group": 0,
      "instanceID": "58e291cf-14c8-4bcd-bf4f-f38a2099fd35",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "749b0e6e-a86a-4d2f-a6cf-4ab08d4d570d",
  "name": "SideJobFinanceInvestigatorOffice-DEfaultMessage"
}