{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "c94d1d51-d9e4-4cf9-947f-639f02c13aa1",
      "forceScope": 0,
      "group": 0,
      "instanceID": "2bc0e315-765c-4915-b868-48d2edd0fb4a",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "e554b94a-670a-4643-93f5-f7f6dc978244",
      "forceScope": 0,
      "group": 0,
      "instanceID": "8c9a9bee-70e4-4a24-add1-3f60b01c9126",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "a2e9fbc2-8934-4096-a41b-f24148e46b8e",
      "forceScope": 0,
      "group": 0,
      "instanceID": "6a1111b1-b296-4f5b-838b-249f5b8ae5e7",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "1d55e841-dbda-4c3e-842d-1126a4e9652c",
      "forceScope": 0,
      "group": 0,
      "instanceID": "761ec9c0-fe97-446c-b669-d5bc598db687",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "985a7aed-1342-46f2-8e7e-2c417d69fa48",
      "forceScope": 0,
      "group": 0,
      "instanceID": "03d9e29c-0350-4355-984a-c1294a39fcba",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "ce86e4a2-6819-415c-8105-ee624d6f9593",
  "name": "SideJobFinanceInvestigatorOffice-InvoiceRequirements"
}